name = "Pumpkin's Hypixel Skyblock Fabric Pack"
author = "PumpkinXD"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b031da9ae5c5436c21b3b8a29ef50d8e25edcd52fbdc65f47bfe3f933744ac3"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.1", "1.21.6"]
